name: Deploy Full Stack Project

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Install root dependencies
      - name: Install Root Dependencies
        run: npm install

      # Install server dependencies
      - name: Install Server Dependencies
        run: |
          cd Server
          npm install

      # Install client dependencies
      - name: Install Client Dependencies
        run: |
          cd eduPlatform
          npm install

      # Build the client
      - name: Build Client
        run: |
          cd eduPlatform
          npm run build -- --base=/EduPlatform-MinzLong/

      # Archive the build artifacts
      - name: Archive artifact
        shell: sh
        run: |
          tar \
            --dereference --hard-dereference \
            --directory "eduPlatform/dist" \
            -cvf "$RUNNER_TEMP/artifact.tar" \
            --exclude=.git \
            --exclude=.github \
            .

      # Upload the build artifacts
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: ${{ runner.temp }}/artifact.tar
          if-no-files-found: error

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Install Heroku CLI
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh

      - name: Login to Heroku
        run: echo ${{ secrets.HEROKU_API_KEY }} | heroku auth:token

      - name: Deploy to Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          heroku create ${{ github.repository }}-server
          git push heroku master

  check-logs:
    runs-on: ubuntu-latest
    if: failure()
    steps:
      - name: Check Server Logs
        run: docker logs ${{ steps.get-server-id.outputs.id }}
